# Crie uma função chamada dados_pessoais que receba
#  informações de uma pessoa (nome, idade, cidade, etc.)
#  usando **kwargs e imprima cada dado em uma linha. Exemplo de chamada:

# dados_pessoais(nome="Ana", idade=25, cidade="Recife")


def dados_pessoais(**cadastro):
    for chave, valor in cadastro.items():
        print(f"{chave}: {valor}")
    return


dados_pessoais(nome="Ana", idade=25, cidade="Recife")
